### ISSUE TITLE
check_disk.sh: line 110: [: UtilisÃ© : nombre entier attendu comme expression check_disk.sh: line 112: [: UtilisÃ© : nombre entier attendu comme expression check_disk.sh: line 115: [: UtilisÃ© : nombre entier attendu comme expression

### ISSUE THREAD

**Issue by bartounet16** [eddimas/nagios-plugins#2]
I have this error.
Script does not support decimal ?

rootfs                -       -     -    - /
sysfs                 0       0     0    - /sys
proc                  -       -     -    - /proc
udev                11M       0   11M   0% /dev
devpts                0       0     0    - /dev/pts
tmpfs              1,7G    8,9M  1,7G   1% /run
/dev/sda1          512G    8,6G  477G   2% /
securityfs            0       0     0    - /sys/kernel/security
tmpfs                 -       -     -    - /dev/shm
tmpfs              5,3M       0  5,3M   0% /run/lock
tmpfs              4,2G       0  4,2G   0% /sys/fs/cgroup
cgroup                0       0     0    - /sys/fs/cgroup/systemd
pstore                0       0     0    - /sys/fs/pstore
cgroup                0       0     0    - /sys/fs/cgroup/cpuset
cgroup                0       0     0    - /sys/fs/cgroup/cpu,cpuacct
cgroup                0       0     0    - /sys/fs/cgroup/devices
cgroup                0       0     0    - /sys/fs/cgroup/freezer
cgroup                0       0     0    - /sys/fs/cgroup/net_cls,net_prio
cgroup                0       0     0    - /sys/fs/cgroup/blkio
cgroup                0       0     0    - /sys/fs/cgroup/perf_event
systemd-1             -       -     -    - /proc/sys/fs/binfmt_misc
mqueue                0       0     0    - /dev/mqueue
debugfs               0       0     0    - /sys/kernel/debug
hugetlbfs             0       0     0    - /dev/hugepages
udev                11M       0   11M   0% /opt/olfeo/chroot/dev
/proc                 0       0     0    - /opt/olfeo/chroot/proc
rpc_pipefs            0       0     0    - /run/rpc_pipefs
tmpfs              269M       0  269M   0% /opt/olfeo/chroot/tmp/ram
shm                4,2G       0  4,2G   0% /opt/olfeo/chroot/dev/shm
shm                4,2G       0  4,2G   0% /dev/shm
binfmt_misc           0       0     0    - /proc/sys/fs/binfmt_misc

**Comment by bartounet16** [comment]
i understand it is because my os is in french

**Comment by eddimas** [comment]
I realize the script doesn't filter the following kind of FS:
```
/proc 0 0 0 - /opt/olfeo/chroot/proc
rpc_pipefs 0 0 0 - /run/rpc_pipefs
```
Anyway I apply the filter and now its working properly.
Br
